/**
* @File Name : GiftAidSubmissionController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 20, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 20, 2025 |   | Initial Version
**/

public class GiftAidSubmissionController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}